### ISSUE TITLE
m32

### ISSUE THREAD

**Issue by rofl0r** [MrAlert/sdlcl#11]
why the heck do you hardcode -m32 in the makefile ? i just wasted half an hour debugging this error

```
In file included from /include/SDL2/SDL_main.h:25:0,
                 from /include/SDL2/SDL.h:32,
                 from SDL2.h:27,
                 from main.c:27:
/include/SDL2/SDL_stdinc.h:265:20: error: size of array 'SDL_dummy_uint64' is negative
        typedef int SDL_dummy_ ## name[(x) * 2 - 1]
                    ^
/include/SDL2/SDL_stdinc.h:274:1: note: in expansion of macro 'SDL_COMPILE_TIME_ASSERT'
 SDL_COMPILE_TIME_ASSERT(uint64, sizeof(Uint64) == 8);
 ^~~~~~~~~~~~~~~~~~~~~~~
/include/SDL2/SDL_stdinc.h:265:20: error: size of array 'SDL_dummy_sint64' is negative
        typedef int SDL_dummy_ ## name[(x) * 2 - 1]
                    ^
/include/SDL2/SDL_stdinc.h:275:1: note: in expansion of macro 'SDL_COMPILE_TIME_ASSERT'
 SDL_COMPILE_TIME_ASSERT(sint64, sizeof(Sint64) == 8);
 ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [main.o] Error 1

```

**Comment by strycore** [comment]
hmm, because 99% of SDL1.2 games are 32bit?

**Comment by rofl0r** [comment]
huh ? they are whatever bit the system has you compile it for

**Comment by strycore** [comment]
If the game is compiled then it means it's open source and it might as well be ported to SDL2 directly instead of relying on SDLCL. 
The purpose of this library is to fix games we don't have source code access to.

**Comment by rofl0r** [comment]
well, i'm currently trying to figure out if this can be used to fix the "fullscreen-window-not-stretched-to-fullscreen" issue i reported here https://github.com/lutris/libfswindow/issues/1#issuecomment-302540335, and i do so with https://github.com/a-nikolaev/curseofwar https://github.com/rofl0r/openbor https://github.com/rofl0r/opendow and all of them are open source but i cant even tell yet if using SDL2 will fix the issue, and even if it will, i dunno if i'll ever have time to port them to SDL2. anyway, hardcoding a specific arch in a makefile is a very bad idea, usually the user has to set that explicitly using his CC variable.
ex:
```
make CC="gcc -m32" -j4
```

**Comment by strycore** [comment]
I'll let @MrAlert decide on the `-m32` thing. As for the games, I would indeed suggest to port them to SDL2  as is has much better support for screen handling, I'm pretty sure using SDL2 will fix your issue. 
The process of porting to SDL2 is so simple that even I managed to port a game and I'm a terrible C coder! (See https://github.com/lutris/rRootage )

**Comment by rofl0r** [comment]
as of right now, it looks not good.
running openbor fails with:
```
Error relocating ./OpenBOR: SDL_GetKeyName: symbol not found
```
and the other 2 crash because glXGetCurrentContext() returns NULL in
__glXSetupForCommand (dpy=0x623cc0) at glxext.c:971

```
969        /* If this thread has a current context, flush its rendering commands */
970        gc = __glXGetCurrentContext();
971        if (gc->currentDpy) {

```

**Comment by MaddTheSane** [comment]
Not all SDL 1.2 symbols are implemented.
On May 18, 2017, at 3:54 PM, rofl0r <notifications@github.com<mailto:notifications@github.com>> wrote:


as of right now, it looks not good.
running openbor fails with:

Error relocating ./OpenBOR: SDL_GetKeyName: symbol not found


and the other 2 crash because glXGetCurrentContext() returns NULL in
__glXSetupForCommand (dpy=0x623cc0) at glxext.c:971

969        /* If this thread has a current context, flush its rendering commands */
970        gc = __glXGetCurrentContext();
971        if (gc->currentDpy) {

**Comment by strycore** [comment]
The project is still a work in progress, see https://github.com/MrAlert/sdlcl/issues/8 for the implemented functions (SDL_GetKeyName still needs to be implemented)

For the other crashes, maybe it's related to this: https://github.com/MrAlert/sdlcl/issues/10 
Rune, which I could run previously now crashes in what seems to be OpenGL initialization. You could try rolling back 1 commit (but you won't have window stretching which is precisely what you're looking for)

**Comment by rofl0r** [comment]
it seems the crash i get is unrelated to this repo, i got the exact same crash when i compiled openbor with opengl on. i recently updated mesalib, so maybe its a new bug in mesalib or an incompabitility with one of the other X11 libs or xorg-server itself.

**Comment by MrAlert** [comment]
I accidentally removed -m32 in c274832d864e07e4d8b25045f3ffdc071f1f9a88 as I was testing 64-bit BZFlag at the time. It's just as well, though, because compiling it to 32-bit is as simple as `make CC="gcc -m32"`.
