### ISSUE TITLE
Unreal Tournament 2004 resolutions unavailable

### ISSUE THREAD

**Issue by rea987** [MrAlert/sdlcl#20]
Greetings @MrAlert ,

Currently, in both 32bit and 64bit mode, UT2k4's resolutions are unavailable in game's **Settings > Display** menu. Only available resolution is 800x600.

![ekran goruntusu 2018-12-01 01-05-17](https://user-images.githubusercontent.com/1547646/49317476-ac59ad80-f505-11e8-9865-26fed8f0cafc.png)

The resolution can be changed via editing ~/.ut2004/System/**UT2004.ini** but game warns about incompatible resolution in the same menu.

![ekran goruntusu 2018-10-29 22-43-37](https://user-images.githubusercontent.com/1547646/49317600-2e49d680-f506-11e8-8969-e2eeacbeb86b.png)

Despite the warning, the game launches and runs fine.

Specs:
Distro: Mint 19 x64 Mate
Kernel: Linux 4.15.0-39
GPU: Nvidia 940M (396.54.09)
CPU: Intel i5-6200U

**Comment by MrAlert** [comment]
Fixed it here (f7530d684bc7867e05e2e71385a452f26ba29555). Apparently, UT 2004 doesn't ask for a list of valid video modes using `SDL_ListModes` but instead checks a bunch of predefined modes with `SDL_VideoModeOK`. It doesn't seem to like it when it responds with a color depth of 24 instead of 32.
