### ISSUE TITLE
[Wayland] Cannot start ut2004

### ISSUE THREAD

**Issue by TRPB** [MrAlert/sdlcl#24]
This works fine in Xorg, but under Wayland I cannot start UT2004.

Running ut2004 with sdlcl gives:

```
Couldn't set video mode: Couldn't find matching GLX visual


History: 

Exiting due to error
```

`SDL_VIDEODRIVER=x11` has no effect.

Setting `SDL_VIDEO_X11_VISUALID=` does something as it gives a different error: 

```
Couldn't set video mode: Could not create GL context


History: 

Exiting due to error


```

Finally, `SDL_VIDEODRIVER=wayland` appears to get the least furthest as it gives the error:

```
Error loading GL: OpenGL library already loadedOpenGL library already loaded

History: 

Exiting due to error
```

**Comment by TRPB** [comment]
After further trial and error, this is the same as #22 , the game won't start if antialiasing is enabled.

**Comment by the-burrito-triangle** [comment]
With the current [`sdl12-compat-1.2.70`](https://github.com/libsdl-org/sdl12-compat/releases/tag/release-1.2.70), UT2004 works natively with Wayland using `SDL_VIDEODRIVER=wayland`, but has issues with [uncontrolled framerate](https://github.com/libsdl-org/sdl12-compat/issues/379) and lower performance than `sdlcl`. Would be nice if fixes from `sdlcl` could be ported over to `sdl12-compat` (or vice-versa) so UT2004 can play natively on Wayland.
