### ISSUE TITLE
Dungeons of Dredmor needs SDL_SetColors

### ISSUE THREAD

**Issue by rohit-n** [MrAlert/sdlcl#4]
`./Dredmor-amd64: symbol lookup error: ./Dredmor-amd64: undefined symbol: SDL_SetColors`

**Comment by rohit-n** [comment]
Update:

`./Dredmor-amd64: undefined symbol: SDL_ConvertSurface`

**Comment by rohit-n** [comment]
nm -D Dredmor-amd64 outputs:

`                 U access
00000000005e8110 T adler32
00000000005e8480 T adler32_combine
                 U alBufferData
                 U alcCloseDevice
                 U alcCreateContext
                 U alcDestroyContext
                 U alcGetContextsDevice
                 U alcGetCurrentContext
                 U alcMakeContextCurrent
                 U alcOpenDevice
                 U alcProcessContext
                 U alcSuspendContext
                 U alDeleteBuffers
                 U alDeleteSources
                 U alGenBuffers
                 U alGenSources
                 U alGetEnumValue
                 U alGetSourcei
                 U alGetString
                 U alIsExtensionPresent
                 U alSourcef
                 U alSourcei
                 U alSourcePlay
                 U alSourceQueueBuffers
                 U alSourceStop
                 U alSourceUnqueueBuffers
00000000008c5ba0 A __bss_start
                 U ceilf
                 U clearerr
                 U close
                 U closedir
                 U cos
00000000005e8780 T crc32
00000000005e8a60 T crc32_combine
                 U __ctype_toupper_loc
                 U __cxa_atexit
                 U __cxa_begin_catch
                 U __cxa_end_catch
                 U __cxa_guard_abort
                 U __cxa_guard_acquire
                 U __cxa_guard_release
                 U __cxa_pure_virtual
                 U __cxa_rethrow
                 U __dynamic_cast
00000000008c5ba0 A _edata
00000000008d0ac8 A _end
0000000000420b10 T erf
0000000000420d30 T erfc
                 U __errno_location
                 U exit
                 U exp
                 U fclose
                 U fdopen
                 U feof
                 U ferror
                 U fflush
                 U fgets
                 U fileno
000000000063d5f0 T _fini
                 U floor
                 U floorf
                 U fopen64
                 U fprintf
                 U fputc
                 U fread
                 U free
                 U fseek
                 U fsync
                 U ftell
                 U fwrite
                 U __fxstat64
00000000005e8770 T get_crc_table
                 U getcwd
                 U getenv
                 U getpid
                 U getpwuid
                 U getuid
                 w __gmon_start__
                 U __gxx_personality_v0
00000000005ecf10 T inflate
00000000005eeea0 T inflateCopy
000000000066a440 R inflate_copyright
00000000005eea40 T inflateEnd
00000000005ec220 T inflate_fast
00000000005eeba0 T inflateGetHeader
00000000005ece70 T inflateInit_
00000000005ecd50 T inflateInit2_
00000000005ecd00 T inflatePrime
00000000005ecc50 T inflateReset
00000000005eea90 T inflateSetDictionary
00000000005eebd0 T inflateSync
00000000005eee70 T inflateSyncPoint
00000000005ef040 T inflate_table
00000000004053f8 T _init
                 U isalpha
                 w _Jv_RegisterClasses
                 U ldexp
                 U __libc_start_main
                 U log
                 U logf
                 U lseek64
                 U __lxstat64
                 U malloc
                 U memcmp
                 U memcpy
                 U memmove
                 U memset
                 U mkdir
                 U mktime
                 U mmap64
                 U munmap
                 U open64
                 U opendir
                 U pow
                 U printf
                 w pthread_cancel
                 U pthread_mutex_destroy
                 U pthread_mutex_init
                 U pthread_mutex_lock
                 U pthread_mutex_unlock
                 U pthread_self
                 U putenv
                 U puts
                 U qsort
                 U rand
                 U read
                 U readdir64
                 U readlink
                 U realloc
                 U realpath
                 U remove
                 U SDL_ConvertSurface
                 U SDL_CreateMutex
                 U SDL_CreateRGBSurface
                 U SDL_CreateThread
                 U SDL_Delay
                 U SDL_DestroyMutex
                 U SDL_EnableUNICODE
                 U SDL_FillRect
                 U SDL_Flip
                 U SDL_FreeSurface
                 U SDL_GetError
                 U SDL_GetModState
                 U SDL_GetMouseState
                 U SDL_GetTicks
                 U SDL_GL_GetProcAddress
                 U SDL_GL_LoadLibrary
                 U SDL_GL_SwapBuffers
                 U SDL_Init
                 U SDL_Linked_Version
                 U SDL_ListModes
                 U SDL_LoadBMP_RW
                 U SDL_LockSurface
                 U SDL_MapRGB
                 U SDL_mutexP
                 U SDL_mutexV
                 U SDL_PollEvent
                 U SDL_PumpEvents
                 U SDL_Quit
                 U SDL_RWFromFile
                 U SDL_SaveBMP_RW
                 U SDL_SetAlpha
                 U SDL_SetClipRect
                 U SDL_SetColorKey
                 U SDL_SetColors
                 U SDL_SetVideoMode
                 U SDL_ShowCursor
                 U SDL_UnlockSurface
                 U SDL_UpperBlit
                 U SDL_WaitThread
                 U SDL_WM_SetCaption
                 U sin
                 U sincos
                 U snprintf
                 U sprintf
                 U srand
00000000008c5e70 B stderr
00000000008c5e80 B stdout
                 U strcasecmp
                 U strcat
                 U strchr
                 U strcmp
                 U strcpy
                 U strerror
                 U strlen
                 U strncasecmp
                 U strncmp
                 U strncpy
                 U strrchr
                 U strstr
                 U strtod
                 U strtol
                 U strtoull
                 U system
                 U tolower
                 U toupper
                 U TTF_Init
                 U TTF_OpenFont
                 U TTF_Quit
                 U TTF_RenderUTF8_Blended
                 U TTF_SizeUTF8
                 U unlink
                 U _Unwind_Resume
                 U utimes
                 U vfprintf
                 U vsnprintf
                 U write
                 U __xstat64
00000000005efa50 T zcalloc
00000000005efa60 T zcfree
                 U _ZdaPv
                 U _ZdlPv
000000000066a5e0 R z_errmsg
00000000005efa30 T zError
00000000005efa20 T zlibCompileFlags
00000000005efa10 T zlibVersion
                 U _Znam
                 U _ZNKSs12find_last_ofEPKcmm
                 U _ZNKSs16find_last_not_ofEPKcmm
                 U _ZNKSs4findEcm
                 U _ZNKSs4findEPKcmm
                 U _ZNKSs5rfindEPKcmm
                 U _ZNKSs7compareEmmRKSs
                 U _ZNKSs7compareEPKc
                 U _ZNKSt5ctypeIcE13_M_widen_initEv
                 U _ZNSi5tellgEv
                 U _ZNSirsERi
                 U _ZNSolsEi
                 U _ZNSs12_M_leak_hardEv
                 U _ZNSs14_M_replace_auxEmmmc
                 U _ZNSs4_Rep10_M_destroyERKSaIcE
00000000008c5e50 V _ZNSs4_Rep20_S_empty_rep_storageE
                 U _ZNSs4_Rep9_S_createEmmRKSaIcE
                 U _ZNSs4swapERSs
                 U _ZNSs6appendEPKc
                 U _ZNSs6appendEPKcm
                 U _ZNSs6appendERKSs
                 U _ZNSs6assignEPKc
                 U _ZNSs6assignEPKcm
                 U _ZNSs6assignERKSs
                 U _ZNSs6resizeEmc
                 U _ZNSs7reserveEm
                 U _ZNSs9_M_mutateEmmm
                 U _ZNSsC1EmcRKSaIcE
                 U _ZNSsC1EPKcmRKSaIcE
                 U _ZNSsC1EPKcRKSaIcE
                 U _ZNSsC1ERKSs
                 U _ZNSsC1ERKSsmm
                 U _ZNSsD1Ev
                 U _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEE7_M_syncEPcmm
0000000000448930 W _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEED0Ev
00000000004488c0 W _ZNSt15basic_stringbufIcSt11char_traitsIcESaIcEED1Ev
                 U _ZNSt15_List_node_base11_M_transferEPS_S0_
                 U _ZNSt15_List_node_base7_M_hookEPS_
                 U _ZNSt15_List_node_base9_M_unhookEv
                 U _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev
                 U _ZNSt6localeC1Ev
                 U _ZNSt6localeD1Ev
                 U _ZNSt8ios_base4InitC1Ev
                 U _ZNSt8ios_base4InitD1Ev
                 U _ZNSt8ios_baseC2Ev
                 U _ZNSt8ios_baseD2Ev
                 U _ZNSt9basic_iosIcSt11char_traitsIcEE4initEPSt15basic_streambufIcS1_E
                 U _ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate
                 U _Znwm
                 U _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l
                 U _ZSt16__throw_bad_castv
                 U _ZSt17__throw_bad_allocv
                 U _ZSt18_Rb_tree_decrementPKSt18_Rb_tree_node_base
                 U _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
                 U _ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base
                 U _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base
                 U _ZSt19__throw_logic_errorPKc
                 U _ZSt20__throw_length_errorPKc
                 U _ZSt20__throw_out_of_rangePKc
                 U _ZSt28_Rb_tree_rebalance_for_erasePSt18_Rb_tree_node_baseRS_
                 U _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_
                 U _ZSt2wsIcSt11char_traitsIcEERSt13basic_istreamIT_T0_ES6_
00000000004f10c0 W _ZStplIcSt11char_traitsIcESaIcEESbIT_T0_T1_EPKS3_RKS6_
                 U _ZStrsIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RSbIS4_S5_T1_E
00000000008c5cc0 V _ZTTSt18basic_stringstreamIcSt11char_traitsIcESaIcEE
00000000008c5d10 V _ZTVN10__cxxabiv117__class_type_infoE
00000000008c5d70 V _ZTVN10__cxxabiv120__si_class_type_infoE
00000000008c5dd0 V _ZTVSt15basic_streambufIcSt11char_traitsIcEE
00000000008c5c20 V _ZTVSt15basic_stringbufIcSt11char_traitsIcESaIcEE
00000000008c5ba0 V _ZTVSt18basic_stringstreamIcSt11char_traitsIcESaIcEE
00000000008c5ca0 V _ZTVSt9basic_iosIcSt11char_traitsIcEE
`

**Comment by MrAlert** [comment]
Updated the blending mode and conversion code to better match SDL 1.2's behavior. How does it look now?

**Comment by rohit-n** [comment]
Game now starts, and water and lava render correctly. The game still segfaults on exit on video.c:591, though.

**Comment by rohit-n** [comment]
With the latest commits, Dredmor no longer crashes on exit. All that's left for perfect compatibility (from what I'm seeing) is text input for entering the player's name. I'll close this issue.
